KS-2-5 simple bank calculator
nfedetsky/KotlinSprint pull request #10
Opened 2024-03-12 22:08 UTC by nfedetsky

2024-03-14 11:16 UTC, ievetrovdev requested changes

2024-03-14 11:16 UTC, ievetrovdev commented on src/main/kotlin/less_2/less2_task5.kt
> +    val interestRate = 16.7 / 100
Решение верное, но давай еще инициализируем число 100

2024-03-15 01:14 UTC, nfedetsky commented on src/main/kotlin/less_2/less2_task5.kt
> +    val interestRate = 16.7 / 100
Поправил

2024-03-15 09:04 UTC, ievetrovdev approved these changes

2024-03-15 10:42 UTC, merged