KS-4-2 Cargo comparison
nfedetsky/KotlinSprint pull request #16
Opened 2024-03-18 19:34 UTC by nfedetsky

2024-03-19 09:17 UTC, ievetrovdev requested changes

2024-03-19 09:17 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task2.kt
> +    proposedWeight <= AVERAGE_WEIGHT_MAX && proposedLiquid <= VOLUME_LIQUID}")
Согласно ТЗ: объем меньше 100 литров.

2024-03-19 09:17 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task2.kt
> +    println("Груз с весом $proposedWeight кг и объемом $proposedLiquid л соответствует категории 'Average': ${proposedWeight >= AVERAGE_WEIGHT_MIN &&
Строки слишком длинные (>120 символов), глазу труднее в них ориентироваться. Часто в компаниях вводят правила форматирования, а также специальные утилиты, которые следят за соблюдением правил.

Вот например такая утилита Detekt для Kotlin запрещает по-умолчанию строки длиннее 120 символов: https://detekt.dev/docs/rules/formatting/#maximumlinelength.
Давай добавим перенос или вынесем в переменную условие

2024-03-21 20:09 UTC, nfedetsky commented on src/main/kotlin/less_4/less4_task2.kt
> +    proposedWeight <= AVERAGE_WEIGHT_MAX && proposedLiquid <= VOLUME_LIQUID}")
эммм... Вот условие из задачи
- проверь, соответствуют ли следующие грузы категории "Average": 20 кг / 80 л и 50 кг / 100 л;
Или в чем-то другом ошибка?

2024-03-21 20:10 UTC, nfedetsky commented on src/main/kotlin/less_4/less4_task2.kt
> +    println("Груз с весом $proposedWeight кг и объемом $proposedLiquid л соответствует категории 'Average': ${proposedWeight >= AVERAGE_WEIGHT_MIN &&
Поставил Детект. Изменил код. Результат детекта норм. Вроде справился...

2024-03-22 15:36 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task2.kt
> +    proposedWeight <= AVERAGE_WEIGHT_MAX && proposedLiquid <= VOLUME_LIQUID}")
Все верно, только тут нужна проверка < 100)

2024-03-22 15:42 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task2.kt
> +    println("Груз с весом $proposedWeight кг и объемом $proposedLiquid л соответствует категории 'Average': ${proposedWeight >= AVERAGE_WEIGHT_MIN &&
Строки все еще длинные) Давай добавим переносы

2024-03-22 15:44 UTC, ievetrovdev requested changes

2024-03-22 15:44 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task2.kt
> +    var proposedLiquid: Int
Не ошибка, нно можно инициализировать сразу, а потом перезаписать

2024-03-25 09:10 UTC, ievetrovdev approved these changes

2024-03-25 12:59 UTC, merged