KS-4-3 Growing beans
nfedetsky/KotlinSprint pull request #18
Opened 2024-03-24 18:44 UTC by nfedetsky

2024-03-25 09:22 UTC, ievetrovdev requested changes

2024-03-25 09:22 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task3.kt
> +    val weatherSunny: Boolean = true
Лучше использовать более релевантное название для Boolean переменных, которые являются своеобразным "флагом" состояния. И для них рекомендуемая конструкция такая: isSunny / isAwningOpen

2024-03-25 09:22 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task3.kt
> +    val season: String = "Winter"
Значения с которыми сравниваются критерии стоит вынести в константы, так как они постоянные и не планируются изменяться после компиляции.

2024-03-25 09:22 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task3.kt
> +            (season == seasonCurrently)
По ТЗ благоприятными условиями является - не зима

2024-03-29 22:04 UTC, nfedetsky commented on src/main/kotlin/less_4/less4_task3.kt
> +            (season == seasonCurrently)
Поправил

2024-03-30 08:01 UTC, ievetrovdev requested changes

2024-03-30 08:01 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task3.kt
> +const val SEASON: String = "Spring"
Не зима не значит только весна) 
Смотри, в константе можно хранить значение "Зима", а в коде условия  реализовать отрицание. Так как предполагаем, что нам приходят сухие данные с названием времени года. В ином случае эту программу будет сложно поддерживать и расширять.

2024-03-30 08:34 UTC, nfedetsky commented on src/main/kotlin/less_4/less4_task3.kt
> +const val SEASON: String = "Spring"
Только со второго раза воткнул в логику)) Красиво!)) Спасибо!

2024-03-31 08:19 UTC, ievetrovdev approved these changes

2024-03-31 08:19 UTC, ievetrovdev commented on src/main/kotlin/less_4/less4_task3.kt
> +const val WEATHER_SUNNY: Boolean = true
Все ок, на будущее - для Boolean-констант нейминг соответствующий: IS_WEATHER_SUNNY

2024-04-01 14:52 UTC, merged