KS-1-2 variables part2 number of employees
nfedetsky/KotlinSprint pull request #2
Opened 2024-03-10 21:12 UTC by nfedetsky

2024-03-11 19:54 UTC, ievetrovdev requested changes

2024-03-11 19:54 UTC, ievetrovdev commented on src/main/kotlin/less_1/less1_task2.kt
> +    println("Currently" + space + "there are" + space + productQuant + space + "orders in the internet store")
давай использовать интерполяцию для формирования строк (знак $)

2024-03-11 19:54 UTC, ievetrovdev commented on src/main/kotlin/less_1/less1_task2.kt
> +    println("Currently" + space + "there are" + space + numberOfEmployees + space + "employees in the internet store")
также нужно предыдущий вывод закомментировать по условию)

2024-03-11 20:13 UTC, nfedetsky commented on src/main/kotlin/less_1/less1_task2.kt
> +    println("Currently" + space + "there are" + space + productQuant + space + "orders in the internet store")
Удалил переменную space, откорректировал текстовые строки

2024-03-11 20:14 UTC, nfedetsky commented on src/main/kotlin/less_1/less1_task2.kt
> +    println("Currently" + space + "there are" + space + numberOfEmployees + space + "employees in the internet store")
Закомментировал "старый" вывод

2024-03-12 07:20 UTC, ievetrovdev approved these changes

2024-03-12 07:20 UTC, ievetrovdev commented on src/main/kotlin/less_1/less1_task2.kt
> +    println(gratitudeText)
теперь все супер)

2024-03-12 20:37 UTC, merged