KS-5-2 age check
nfedetsky/KotlinSprint pull request #21
Opened 2024-03-24 21:06 UTC by nfedetsky

2024-03-30 08:05 UTC, ievetrovdev requested changes

2024-03-30 08:05 UTC, ievetrovdev commented on src/main/kotlin/less_5/less5_task2.kt
> +    val userYearBirth = readln()!!.toInt()
Использование оператора !! подразумевает, что ты уверен в том, что значение не может быть null. Однако, если это не так, то приложение "упадет" с ошибкой. Поэтому этот оператор считается опасным и не рекомендуется использовать. Только в крайних случаях.

2024-03-30 08:42 UTC, nfedetsky commented on src/main/kotlin/less_5/less5_task2.kt
> +    val userYearBirth = readln()!!.toInt()
Ну да... Я просто взял этот кусок кода из тренировочного проекта, который делал, смотря твой ролик по этому уроку.. Убрал.

2024-03-31 08:21 UTC, ievetrovdev approved these changes

2024-04-01 14:53 UTC, merged