Less5 task3
nfedetsky/KotlinSprint pull request #22
Opened 2024-03-29 21:01 UTC by nfedetsky

2024-03-31 08:30 UTC, ievetrovdev requested changes
Тут нарушена логика игры: а что будет, если пользователь введет числа в обратном порядке? или, к примеру, введет второе число первым, в первое не угадает? Давай доработаем, учтем все варианты

2024-05-19 14:08 UTC, nfedetsky commented
Вроде поправил. Проверил в разных вариантах - выполняет задание

2024-05-19 16:00 UTC, ievetrovdev requested changes

2024-05-19 16:00 UTC, ievetrovdev commented on src/main/kotlin/less_5/less5_task3.kt
> +    println(message = "Input the second number:  ")
Попробуй сначала ввести оба числа, а замет написать условие на проверку главного приза, и утешительного. Это будет более верным и простым подходом в данном случае. То есть сначала  все  данные,  затем проверка на каждый кейс.

2024-05-19 18:12 UTC, nfedetsky commented on src/main/kotlin/less_5/less5_task3.kt
> +    println(message = "Input the second number:  ")
Сделал. Смотри.

2024-05-20 07:02 UTC, ievetrovdev requested changes
Нужны исправления

2024-05-20 07:02 UTC, ievetrovdev commented on src/main/kotlin/less_5/less5_task3.kt
> +    else if ((inputLuckyNumberOne == luckyNumberOne && inputLuckyNumberTwo != luckyNumberTwo) ||
Если inputLuckyNumberTwo = 42 то утешительного приза не будет. Давай лучше что то похожее на 
inputLuckyNumberOne == luckyNumberOne || inputLuckyNumberTwo == luckyNumberTwo в условие сделаем, будет проще проверить

2024-05-21 22:12 UTC, nfedetsky commented on src/main/kotlin/less_5/less5_task3.kt
> +    else if ((inputLuckyNumberOne == luckyNumberOne && inputLuckyNumberTwo != luckyNumberTwo) ||
Сделал третий вариант. Надеюсь, уже правильный))

2024-05-22 06:47 UTC, ievetrovdev approved these changes
Отлично, дожали, теперь все верно!

2024-05-22 15:14 UTC, merged