KS-6-1 The first version the user authorization
nfedetsky/KotlinSprint pull request #26
Opened 2024-05-23 23:18 UTC by nfedetsky

2024-05-24 20:16 UTC, ievetrovdev requested changes

2024-05-24 20:16 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task1.kt
> +        if (i > 0) println("Authorization failed. Try again")
Использовать для таких целей переменную счетчик - плохая идея. Давай заменим это обычным условием, которое уже есть в while, можно сделать флаг, и использовать его везде где необходимо учесть прохождение или не прохождение авторизации.

2024-05-24 20:16 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task1.kt
> +    userLogin = readln().toString()
Приведение к .toString() тут избыточно, потому что функция readln() уже возвращает строку (среда разработки предлагает удалить, чтобы улучшить читаемость кода и избежать лишней операции).

2024-05-24 21:32 UTC, nfedetsky commented on src/main/kotlin/less_6/less6_task1.kt
> +    userLogin = readln().toString()
Сделал два фикса - в первом забыл удалить toString. А вообще, по первому замечанию - да, что-то не дотумкал сам, что так можно было((

2024-05-25 05:42 UTC, ievetrovdev requested changes

2024-05-25 05:42 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task1.kt
> +        userInputLogin = readln().toString()
Приведение к .toString() тут избыточно, потому что функция readln() уже возвращает строку (среда разработки предлагает удалить, чтобы улучшить читаемость кода и избежать лишней операции).

2024-05-26 00:40 UTC, nfedetsky commented on src/main/kotlin/less_6/less6_task1.kt
> +        userInputLogin = readln().toString()
Поправил)

2024-05-26 07:03 UTC, ievetrovdev requested changes

2024-05-26 07:03 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task1.kt
> +    var i = 0
Давай не будем создавать лишних переменных.

2024-05-26 22:46 UTC, ievetrovdev approved these changes
Все верно, отличная работа!

2024-05-26 22:48 UTC, merged