KS-6-2 The first version of counter
nfedetsky/KotlinSprint pull request #27
Opened 2024-05-25 00:44 UTC by nfedetsky

В задании написано, что программа должна встать на паузу, я понимаю это, как после всех расчетов и выводов программа встает на паузу и ждет какой-то команды (хотя бы нажатие на Enter). Не смог в библиотеках Kotlin найти метод, который бы останавливал выполнение приложения до выполнения какого-то действия пользователя.(( Анонимус говорит, что такого метода в Kotlin отродясь не бывало...
Посерчил форумы. На одном из них тот же Анонимус предлагал, если нельзя, но очень хочется, то можно попробовать применить библиотеки java, где есть подобный метод.
Попробовал такую конструкцию:
<код>
val lockPause = java.lang.Object() //Это из java
<код>
//В самом конце
lockPause.wait() //По идее, этот метод подходит, но...
Но получил ошибку, что текущий поток не является овнером. Не стал уже дальше копать, вполне возможно, что мой путь тупиковый и решил, Иван, с тобой проконсультироваться.
В итоге применил Tread.sleep(), но мне кажется, что это не совсем то, так?

2024-05-25 05:44 UTC, ievetrovdev requested changes

2024-05-25 05:44 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task2.kt
> +        while (secTimer > 0) {
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2024-05-26 00:32 UTC, nfedetsky commented on src/main/kotlin/less_6/less6_task2.kt
> +        while (secTimer > 0) {
Возможно я не совсем понял задачу... Но вот что получилось после правки.

2024-05-26 07:01 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-05-26 10:28 UTC, merged