KS-6-4 The first version of The funny game
nfedetsky/KotlinSprint pull request #29
Opened 2024-05-27 01:15 UTC by nfedetsky

2024-05-27 07:44 UTC, ievetrovdev requested changes

2024-05-27 07:44 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task4.kt
> +    do {
Согласно [конвенции стиля Котлин](https://kotlinlang.org/docs/coding-conventions.html) циклы лучше обосабливать пустыми разделяющими строками сверху и снизу. Чтобы код не выглядел таким монолитным)

2024-05-27 07:44 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task4.kt
> +    val hiddenNumber = Random.nextInt(1, 10)
Для рандома можно использовать запись с помощью экстеншн функции random(). И импорт использовать не придется. Она применяется, например, к диапазону 1..9

2024-05-29 21:37 UTC, nfedetsky commented on src/main/kotlin/less_6/less6_task4.kt
> +    val hiddenNumber = Random.nextInt(1, 10)
Я не очень понял необходимость здесь использования экстеншн функции))) тем более, что все равно подтягивается библиотека random. Да и на видео уроке тоже происходит импорт (только там джававская библиотека подтягивается..)
Я попробовал сделать, как понял. Возможно, не то, но хоть с чего-то надо начать постижение этого знания))

2024-05-30 12:38 UTC, ievetrovdev requested changes

2024-05-30 12:38 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task4.kt
> +fun Random.extRandomFunction(): Int {
Это тут не нужно.

2024-05-30 12:38 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task4.kt
> +    val hiddenNumber = Random.extRandomFunction()
(1..9).random()

2024-05-30 12:38 UTC, ievetrovdev commented on src/main/kotlin/less_6/less6_task4.kt
> +    val hiddenNumber = Random.extRandomFunction()
Вот так можно сделать.

2024-05-30 21:02 UTC, nfedetsky commented on src/main/kotlin/less_6/less6_task4.kt
> +    val hiddenNumber = Random.extRandomFunction()
Реально не знал об этой фиче. Искал по всем котлинским "святцам", но нигде этот инструмент работы с рандомной функцией не описан. Иван, спасибо большое!)

2024-05-30 21:07 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-05-30 21:12 UTC, merged