KS-1-3 variables part 3 Outputting the start and end times of flight
nfedetsky/KotlinSprint pull request #3
Opened 2024-03-10 22:32 UTC by nfedetsky

2024-03-11 20:00 UTC, ievetrovdev requested changes

2024-03-11 20:00 UTC, ievetrovdev commented on src/main/kotlin/less_1/less1_task3.kt
> +    println("Year of flight:" + space + yearOfGFlight)
давай везде использовать интерполяцию для вывода строк ($)

2024-03-11 20:00 UTC, ievetrovdev commented on src/main/kotlin/less_1/less1_task3.kt
> +    print(hour)
давай здесь тоже использовать $

2024-03-11 20:25 UTC, nfedetsky commented on src/main/kotlin/less_1/less1_task3.kt
> +    println("Year of flight:" + space + yearOfGFlight)
Привел в порядок код

2024-03-12 07:22 UTC, ievetrovdev approved these changes

2024-03-12 20:37 UTC, merged