KS-7-5 password generator second ver.1
nfedetsky/KotlinSprint pull request #35
Opened 2024-06-13 10:56 UTC by nfedetsky

2024-06-13 20:32 UTC, ievetrovdev requested changes

2024-06-13 20:32 UTC, ievetrovdev commented on src/main/kotlin/less_7/less7_task5.kt
> +            tempArray.add(passSimbol.random())
Вместо перечисления всех символов, можно использовать символьные диапазоны и складывать их вместе для получения одного общего набора символов. Например, вот так val allChars = ('a'..'z') + ('A'..'Z') + ('0'..'9')

2024-06-13 22:13 UTC, nfedetsky commented on src/main/kotlin/less_7/less7_task5.kt
> +            tempArray.add(passSimbol.random())
Да... так значительно проще выглядит код, не так монструозно)

2024-06-14 19:01 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-06-14 19:05 UTC, merged