KS-1-4 variables part 4 The metrics of Gagarin's flight
nfedetsky/KotlinSprint pull request #4
Opened 2024-03-10 23:14 UTC by nfedetsky

2024-03-12 06:21 UTC, ievetrovdev requested changes

2024-03-12 06:21 UTC, ievetrovdev commented on src/main/kotlin/less_1/less1_task4.kt
> +    val partOfDay: Double = 0.075
Полагаю есть еще меньше дробный тип, чем Double)

2024-03-12 19:58 UTC, nfedetsky commented on src/main/kotlin/less_1/less1_task4.kt
> +    val partOfDay: Double = 0.075
Пофиксил)) Не сразу доперло, но почитал дополнительные статейки про явное объявление переменных типа Float, понимание пришло.

2024-03-13 17:48 UTC, ievetrovdev approved these changes

2024-03-13 18:13 UTC, merged