KS-1-5 variables part 5 Calculation of flight time
nfedetsky/KotlinSprint pull request #5
Opened 2024-03-10 23:57 UTC by nfedetsky

2024-03-12 06:24 UTC, ievetrovdev requested changes

2024-03-12 06:24 UTC, ievetrovdev commented on src/main/kotlin/less_1/less1_task5.kt
> +    println("$timeHour:$timeMin:$timeSec")
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-03-12 06:24 UTC, ievetrovdev commented on src/main/kotlin/less_1/less1_task5.kt
> +    timeMin = (timeSec / 60 % 60).toByte()
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-03-12 20:09 UTC, nfedetsky commented on src/main/kotlin/less_1/less1_task5.kt
> +    timeMin = (timeSec / 60 % 60).toByte()
Это поправил

2024-03-13 17:51 UTC, ievetrovdev approved these changes

2024-03-13 18:14 UTC, merged