KS-2-1 Calculation part 1 GPA calculation
nfedetsky/KotlinSprint pull request #6
Opened 2024-03-11 00:28 UTC by nfedetsky

2024-03-13 16:32 UTC, ievetrovdev requested changes
Комментированный код лучше не оставлять, если на это нет действительно веских причин. Предлагаю почистить.

2024-03-13 16:32 UTC, ievetrovdev commented on src/main/kotlin/less_2/less2_task1.kt
> +    val gpa = ((3 + 4 + 3 + 5) / 4).toFloat()
Значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Не лучшая практика. Предлагаю добавить переменные)

2024-03-13 18:28 UTC, nfedetsky commented on src/main/kotlin/less_2/less2_task1.kt
> +    val gpa = ((3 + 4 + 3 + 5) / 4).toFloat()
Ну да... эти задачки делал еще до того, как столкнулся с этим понятием. Пофиксил.

2024-03-14 10:30 UTC, ievetrovdev approved these changes

2024-03-14 10:30 UTC, ievetrovdev commented on src/main/kotlin/less_2/less2_task1.kt
> +    val gpa = ((STUD_THE_FIRST + STUD_THE_SECOND + STUD_THE_THIRD + STUD_THE_FORTH) / SUM_STUDENTS).toFloat()
На будущее, тут достаточно было бы обычных переменных)

2024-03-14 22:54 UTC, merged