KS-2-3 Calculation part 3 calculation of arrival time
nfedetsky/KotlinSprint pull request #8
Opened 2024-03-11 23:07 UTC by nfedetsky

2024-03-13 16:40 UTC, ievetrovdev requested changes
По поводу коментированного кода, отписал ранее, плюс здесь ошибка в расчетах, время прибытия должно быть другое

2024-03-13 16:40 UTC, ievetrovdev commented on src/main/kotlin/less_2/less2_task3.kt
> +    val hourToDestination = timeToDestination / 60
чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-03-14 11:10 UTC, ievetrovdev requested changes
Ошибка в расчетах, время прибытия 17:16

2024-03-14 11:10 UTC, ievetrovdev commented on src/main/kotlin/less_2/less2_task3.kt
> +    //The parameters of train start time
Комментированный код не оставляем!

2024-03-14 23:07 UTC, nfedetsky commented on src/main/kotlin/less_2/less2_task3.kt
> +    //The parameters of train start time
Если вот этот комментарий - //The parameters of train start time
то это просто описание блока.

2024-03-15 00:34 UTC, nfedetsky commented on src/main/kotlin/less_2/less2_task3.kt
> +    //The parameters of train start time
Расчет пофиксил

2024-03-15 08:55 UTC, ievetrovdev commented on src/main/kotlin/less_2/less2_task3.kt
> +    //The parameters of train start time
> Если вот этот комментарий - //The parameters of train start time то это просто описание блока.

Да, это лишнее )

2024-03-15 08:59 UTC, ievetrovdev approved these changes

2024-03-15 10:41 UTC, merged