KS-2-4 Calculation part 4 buffs calculation
nfedetsky/KotlinSprint pull request #9
Opened 2024-03-11 23:16 UTC by nfedetsky

2024-03-14 11:13 UTC, ievetrovdev requested changes

2024-03-14 11:13 UTC, ievetrovdev commented on src/main/kotlin/less_2/less2_task4.kt
> +
В ТЗ фигурирует значение 20 (процентов). Его также надо проинициализировать и только потом производить арифметические операции. Это позволит сделать более гибким и легко изменяемым, если понадобится изменить характеристики, кроме того это опять же магическое число

2024-03-15 01:09 UTC, nfedetsky commented on src/main/kotlin/less_2/less2_task4.kt
> +
Поправил решение

2024-03-15 09:03 UTC, ievetrovdev approved these changes

2024-03-15 10:42 UTC, merged